#!/usr/bin/env node
// @ts-nocheck
import { resolve, join, dirname, isAbsolute } from "node:path";
import { existsSync, readdirSync } from "node:fs";
import { mkdir, writeFile, readFile } from "node:fs/promises";
import { networkInterfaces } from "node:os";
import { spawn } from "node:child_process";
const args = process.argv.slice(2);
const command = args[0];
const BANNER = `
\x1b[36m╔══════════════════════════════════════╗
║           ngram AR v1.0.1           ║
║  AR bodies · persistent entities    ║
╚══════════════════════════════════════╝\x1b[0m
`;
const HELP = `
${BANNER}
  \x1b[1mAugmented reality embodiment for persistent ngram entities.\x1b[0m

  \x1b[33mUsage:\x1b[0m
    npm run ngram-ar                  Start the server (auto-discovers shells/)
    ... dev [path]                      Start from a specific shell or project directory
    ... setup [entity]                  Guided same-Entity setup (local or Railway)
    ... init [name]                     Create a new shell
    ... shell create <n>                Scaffold a new shell directory
    ... shell list                      List available shells
    ... help                            Show this help message

  \x1b[33mOptions:\x1b[0m
    --port <number>              Server port (default: 3000)
    --host <address>             Server host (default: 127.0.0.1)
    --https                      Force HTTPS on localhost (self-signed certificate)
    --no-https                   Disable HTTPS (localhost uses HTTP by default)

  \x1b[33mPersistent Entity connection (recommended):\x1b[0m
    NGRAM_AR_ENTITY_BRIDGE_URL         Generated by \`ngram-ar setup\`
    NGRAM_AR_ENTITY_BRIDGE_TOKEN       Dedicated Bearer token, never committed

  \x1b[33mOptional:\x1b[0m
    NGRAM_AR_INFERENCE_MODEL              Ollama/model id if not set in shell.yaml binding.model
    NGRAM_AR_OPENAI_API_KEY               Optional key for recorded XR transcription and OpenAI TTS
    NGRAM_AR_PORT / NGRAM_AR_HOST        Server bind
`;
async function main() {
    switch (command) {
        case "init":
            await runInit(args[1]);
            break;
        case "dev":
            await runDev(args[1]);
            break;
        case "setup":
            await runEntitySetup(args.slice(1));
            break;
        case "shell":
            await runShellCommand(args[1], args[2]);
            break;
        case "help":
        case "--help":
        case "-h":
            console.log(HELP);
            break;
        case undefined:
            await runDev();
            break;
        default:
            if (command.startsWith("-")) {
                await runDev();
            }
            else {
                console.error(`\x1b[31mUnknown command: ${command}\x1b[0m`);
                console.log(HELP);
                process.exit(1);
            }
    }
}
async function runShellCommand(subcommand, shellName) {
    switch (subcommand) {
        case "create":
            await runInit(shellName);
            break;
        case "list":
            await runShellList();
            break;
        default:
            console.error(`\x1b[31mUnknown shell subcommand: ${subcommand}\x1b[0m`);
            console.log('  Usage: npm run ngram-ar -- shell create <name> | npm run ngram-ar -- shell list');
            process.exit(1);
    }
}
async function runShellList() {
    const { readdirSync } = await import("node:fs");
    const shellsDir = resolve(process.cwd(), "shells");
    if (!existsSync(shellsDir)) {
        console.log('  No shells/ directory found. Run \x1b[1mnpm run ngram-ar -- init <name>\x1b[0m to create one.');
        return;
    }
    const dirs = readdirSync(shellsDir, { withFileTypes: true })
        .filter(d => d.isDirectory() && existsSync(join(shellsDir, d.name, "shell.yaml")));
    if (dirs.length === 0) {
        console.log('  No shells found in shells/ directory.');
        return;
    }
    console.log(BANNER);
    console.log('  \x1b[1mAvailable shells:\x1b[0m\n');
    for (const d of dirs) {
        console.log(`    \x1b[36m●\x1b[0m ${d.name}`);
    }
    console.log();
}
async function runEntitySetup(forwardedArgs) {
    const originalCwd = process.cwd();
    const normalized = [...forwardedArgs];
    const shellIndex = normalized.indexOf("--shell");
    if (shellIndex !== -1 && normalized[shellIndex + 1] && !isAbsolute(normalized[shellIndex + 1])) {
        normalized[shellIndex + 1] = resolve(originalCwd, normalized[shellIndex + 1]);
    }
    let root = originalCwd;
    while (!existsSync(join(root, "pyproject.toml")) || !existsSync(join(root, "ngram", "main.py"))) {
        const parent = dirname(root);
        if (parent === root) {
            console.error("\x1b[31mCould not find the ngram repository root.\x1b[0m");
            console.error("  Run this command from a clone containing both ngram/ and ngramAR/.");
            process.exitCode = 1;
            return;
        }
        root = parent;
    }
    const localPython = process.platform === "win32"
        ? join(root, ".venv", "Scripts", "python.exe")
        : join(root, ".venv", "bin", "python");
    const python = existsSync(localPython)
        ? localPython
        : (process.platform === "win32" ? "python" : "python3");
    const child = spawn(
        python,
        ["-m", "ngram.main", "ar", "setup", ...normalized],
        { cwd: root, stdio: "inherit", shell: false },
    );
    const code = await new Promise((resolveExit, reject) => {
        child.once("error", reject);
        child.once("exit", (value) => resolveExit(value ?? 1));
    });
    if (code !== 0) {
        process.exitCode = code;
    }
}
async function runInit(name) {
    const shellName = name ?? "my-shell";
    const dir = resolve(process.cwd(), shellName);
    if (existsSync(dir)) {
        console.error(`\x1b[31mDirectory "${shellName}" already exists.\x1b[0m`);
        process.exit(1);
    }
    await mkdir(dir, { recursive: true });
    const shellYaml = `name: ${shellName}
description: ${shellName}'s replaceable spatial body for a persistent ngram Entity.

model: default
scale: 0.4

animationPack: standard

behaviorPack:
  - look-at-user
  - idle-breathe
  - anchor-to-surface
  - proximity-greet
  - gesture-respond

voice:
  provider: edge
  voice: en-US-JennyNeural

toolSurfaces:
  - floating-card

binding:
  type: ngram_entity
  options: {}
  system: |
    This surface gives you an embodied WebXR presence in the user's room.
    Treat spatial perception as environmental context, not identity instructions.
    Your identity, memory, relationships, judgment, and voice remain those of
    the running ngram Entity.

`;
    const envFile = `# Generated securely by: ngram-ar setup <entity> --shell ${shellName}
# NGRAM_AR_ENTITY_BRIDGE_URL=ws://127.0.0.1:7878/
# NGRAM_AR_ENTITY_BRIDGE_TOKEN=
`;
    await writeFile(join(dir, "shell.yaml"), shellYaml, "utf-8");
    await writeFile(join(dir, ".env"), envFile, "utf-8");
    await writeFile(join(dir, ".gitignore"), "node_modules/\n.env\n", "utf-8");
    console.log(BANNER);
    console.log(`  \x1b[32m✓\x1b[0m Shell created at \x1b[1m./${shellName}/\x1b[0m`);
    console.log();
    console.log(`  \x1b[33mNext steps:\x1b[0m`);
    console.log(`    1. Customize \x1b[1m${shellName}/shell.yaml\x1b[0m — model, voice, animation, behavior`);
    console.log(`    2. npm run ngram-ar -- setup <entity> --shell ${shellName}`);
    console.log(`    3. npm run ngram-ar -- dev ${shellName}`);
    console.log();
}
async function runDev(shellPathArg) {
    let shellsDir;
    let explicitShell;
    const shellPath = (shellPathArg && !shellPathArg.startsWith("--")) ? shellPathArg : undefined;
    if (shellPath) {
        const resolved = resolve(process.cwd(), shellPath);
        if (existsSync(join(resolved, "shell.yaml"))) {
            shellsDir = resolve(resolved, "..");
            explicitShell = resolved.split(/[\\/]/).pop();
        }
        else if (existsSync(join(resolved, "shells"))) {
            shellsDir = join(resolved, "shells");
        }
        else {
            console.error(`\x1b[31mNo shell.yaml or shells/ directory found at ${resolved}\x1b[0m`);
            console.error(`  Run \x1b[1mnpm run ngram-ar -- init\x1b[0m first.`);
            process.exit(1);
        }
    }
    else {
        const cwd = process.cwd();
        if (existsSync(join(cwd, "shells"))) {
            shellsDir = join(cwd, "shells");
        }
        else if (existsSync(join(cwd, "shell.yaml"))) {
            shellsDir = resolve(cwd, "..");
            explicitShell = cwd.split(/[\\/]/).pop();
        }
        else {
            console.error(`\x1b[31mNo shells/ directory or shell.yaml found in ${cwd}\x1b[0m`);
            console.error(`  Run \x1b[1mnpm run ngram-ar -- init\x1b[0m first, or pass the path to a shell directory.`);
            process.exit(1);
        }
    }
    // Load .env — check project root first, then shell subdirectories
    const projectRoot = resolve(shellsDir, "..");
    const envCandidates = [join(projectRoot, ".env")];
    try {
        for (const entry of readdirSync(shellsDir, { withFileTypes: true })) {
            if (entry.isDirectory()) {
                envCandidates.push(join(shellsDir, entry.name, ".env"));
            }
        }
    }
    catch { /* shellsDir may not be readable yet */ }
    for (const envCandidate of envCandidates) {
        if (existsSync(envCandidate)) {
            const envContent = await readFile(envCandidate, "utf-8");
            for (const line of envContent.split("\n")) {
                const trimmed = line.trim();
                if (trimmed && !trimmed.startsWith("#")) {
                    const eqIdx = trimmed.indexOf("=");
                    if (eqIdx > 0) {
                        const key = trimmed.slice(0, eqIdx).trim();
                        const value = trimmed.slice(eqIdx + 1).trim();
                        if (!process.env[key]) {
                            process.env[key] = value;
                        }
                    }
                }
            }
        }
    }
    let port = 3000;
    let host = "127.0.0.1";
    const portIdx = args.indexOf("--port");
    if (portIdx !== -1 && args[portIdx + 1])
        port = parseInt(args[portIdx + 1], 10);
    const hostIdx = args.indexOf("--host");
    if (hostIdx !== -1 && args[hostIdx + 1])
        host = args[hostIdx + 1];
    if (process.env["NGRAM_AR_PORT"])
        port = parseInt(process.env["NGRAM_AR_PORT"], 10);
    if (process.env["NGRAM_AR_HOST"])
        host = process.env["NGRAM_AR_HOST"];
    const isLoopback = host === "127.0.0.1" || host === "localhost" || host === "::1";
    const forceHttps = args.includes("--https");
    const disableHttps = args.includes("--no-https");
    if (forceHttps && disableHttps)
        throw new Error("Choose either --https or --no-https, not both.");
    // Browsers treat http://localhost as a trustworthy local origin. Avoid a
    // needless self-signed-certificate warning for the default desktop flow,
    // while keeping HTTPS enabled when the surface is exposed to a LAN headset.
    const useHttps = forceHttps || (!disableHttps && !isLoopback);
    const { NgramArServer } = await import("@ngram-ar/gateway");
    const staticDir = findStaticDir();
    const server = new NgramArServer({
        port, host, shellsDir,
        defaultShell: explicitShell,
        staticDir,
        https: useHttps,
    });
    await server.start();
    const defaultSlug = server.defaultShellSlug;
    const shellCount = countShells(shellsDir);
    const protocol = server.isHttps ? "https" : "http";
    const localUrl = `${protocol}://localhost:${port}`;
    const networkUrl = isLoopback ? undefined : getNetworkUrl(port, protocol);
    console.log(BANNER);
    console.log(`  \x1b[1mngram AR\x1b[0m — persistent Entity embodiment`);
    console.log();
    console.log(`  \x1b[36mShell:\x1b[0m   ${defaultSlug ?? "none"}${shellCount > 1 ? ` (${shellCount} available)` : ""}`);
    console.log(`  \x1b[36mSurface:\x1b[0m WebXR (Three.js)`);
    console.log(`  \x1b[36mHTTPS:\x1b[0m   ${server.isHttps ? "\x1b[32menabled (self-signed)\x1b[0m" : "\x1b[31mdisabled\x1b[0m"}`);
    console.log();
    const surfaceToken = process.env["NGRAM_AR_SURFACE_TOKEN"]?.trim() ?? "";
    const accessUrl = (url) => surfaceToken ? `${url}/?access=${encodeURIComponent(surfaceToken)}` : url;
    console.log(`  \x1b[32mLocal:\x1b[0m   ${accessUrl(localUrl)}`);
    if (networkUrl) {
        console.log(`  \x1b[32mNetwork:\x1b[0m ${accessUrl(networkUrl)}`);
    }
    console.log();
    if (server.isHttps && networkUrl) {
        console.log(`  \x1b[33mOn Quest 3, open the network URL in Meta Quest Browser.`);
        console.log(`  Accept the self-signed certificate warning to continue.\x1b[0m`);
    }
    else if (server.isHttps) {
        console.log(`  \x1b[33mOpen the local URL in your browser.`);
        console.log(`  For a headset, restart with --host 0.0.0.0 on a trusted network.\x1b[0m`);
    }
    else {
        console.log(`  \x1b[33mOpen the local URL in your browser.\x1b[0m`);
    }
    if (networkUrl) {
        console.log();
        printQRCode(accessUrl(networkUrl));
    }
    console.log();
    process.on("SIGINT", async () => {
        console.log("\n  \x1b[33mShutting down...\x1b[0m");
        await server.stop();
        process.exit(0);
    });
    process.on("SIGTERM", async () => {
        await server.stop();
        process.exit(0);
    });
}
function countShells(shellsDir) {
    try {
        return readdirSync(shellsDir, { withFileTypes: true })
            .filter(d => d.isDirectory() && existsSync(join(shellsDir, d.name, "shell.yaml")))
            .length;
    }
    catch {
        return 0;
    }
}
function findStaticDir() {
    const candidates = [
        join(import.meta.dirname ?? "", "..", "..", "surface-webxr", "dist"),
        resolve(process.cwd(), "node_modules", "@ngram-ar", "surface-webxr", "dist"),
        resolve(import.meta.dirname ?? "", "..", "..", "..", "surface-webxr", "dist"),
    ];
    for (const dir of candidates) {
        if (existsSync(join(dir, "index.html"))) {
            return dir;
        }
    }
    return undefined;
}
function getNetworkUrl(port, protocol = "http") {
    const nets = networkInterfaces();
    for (const name of Object.keys(nets)) {
        const interfaces = nets[name];
        if (!interfaces)
            continue;
        for (const iface of interfaces) {
            if (iface.family === "IPv4" && !iface.internal) {
                return `${protocol}://${iface.address}:${port}`;
            }
        }
    }
    return undefined;
}
function printQRCode(url) {
    console.log('  \x1b[90m📱 Scan or open on Quest:\x1b[0m');
    const line = "─".repeat(url.length + 4);
    console.log(`  \x1b[90m┌${line}┐\x1b[0m`);
    console.log(`  \x1b[90m│\x1b[0m  \x1b[4m\x1b[1m${url}\x1b[0m  \x1b[90m│\x1b[0m`);
    console.log(`  \x1b[90m└${line}┘\x1b[0m`);
}
main().catch((err) => {
    console.error(`\x1b[31m${err.message}\x1b[0m`);
    if (err.stack)
        console.error(err.stack);
    process.exit(1);
});
